### **1. Import the required packages**

In [1]:
#data reading and manipulation packages
import numpy as np
import pandas as pd

#data visualization packages
import matplotlib.pyplot as plt
import seaborn as sns

#machine learning related packages
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

### **2. Reading and Exploring the data**

1. Import the dataset.
2. Check the shape, info, datatype of the columns.
3. Check for missing value and handle them.
4. Check for duplicates and handle them.
5. Do the encoding of the categorical columns.
6. Check for outliers and deal with them.
7. Any necessary visualizations.

In [2]:
data = pd.read_csv('Boston.csv')

In [3]:
data.head() #print the top 5 rows of the data for a quick inspection

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

- CRIM per capita crime rate by town
- ZN proportion of residential land zoned for lots over 25,000 sq.ft.
- INDUS proportion of non-retail business acres per town
- CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
- NOX nitric oxides concentration (parts per 10 million)
- RM average number of rooms per dwelling
- AGE proportion of owner-occupied units built prior to 1940
- DIS weighted distances to five Boston employment centres
- RAD index of accessibility to radial highways
- TAX full-value property-tax rate per 10,000usd
- PTRATIO pupil-teacher ratio by town
- B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
- LSTAT % lower status of the population

In [4]:
data.shape  #print the total number of rows and columns present in the data

(506, 14)

In [5]:
data.dtypes  #print the datatype of values in each column

crim       float64
zn         float64
indus      float64
chas         int64
nox        float64
rm         float64
age        float64
dis        float64
rad          int64
tax          int64
ptratio    float64
black      float64
lstat      float64
medv       float64
dtype: object

In [6]:
data.isnull().sum(axis = 0) #print the total number of missing values in each column

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
black      0
lstat      0
medv       0
dtype: int64

In [7]:
#check for duplicates
data.duplicated().sum() #print the number of duplicate rows in the data

np.int64(0)

In [8]:
data.drop_duplicates(inplace = True)  #drop the duplicate rows (if any)

#### **Check and remove Outliers**

In [9]:
#function to check for outliers and remove them from the given columns
def remove_outliers(data, columns):
    for column in columns:
        if column in data.columns:
            Q1 = data[column].quantile(0.25)
            Q3 = data[column].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            data = data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]
    return data

In [10]:
data_without_outlier = remove_outliers(data, data.columns)

In [11]:
data.shape  #original data

(506, 14)

In [12]:
data_without_outlier.shape  #dataframe without outlier and we lost lot of rows while outlier cleaning

(214, 14)

There are two ways in which we can deal with outliers:

1. **Outlier Removal (we did this above)**: Means removing the rows which have outliers. The problem with this approach is that we can loose lots of data while doing this.

2. **Data Transformation** : We don't remove the outliers but instead we transform the columns having outliers in such a way that outliers don't behave as outliers.
  - 2.1. Square root transformation.
  - 2.2. Log Transformation.
  - 2.3. Box-Cox Transformation.

### **3. Machine Learning Process**

1. Create X and y variables. Store input columns in X and output column in y.
2. Split the data into training and testing sets.
3. Standardize/Scale the data.
4. Apply the ML Algorithm on the data.
5. Check the performance of the model.
6. Necessary improvements in the model to increase its performance/accuracy.

In [13]:
X = data.drop(columns = 'medv')   #store all the input columns
y = data['medv']  #store the output column

In [14]:
#split the dataset into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 100)

#### **Apply Linear Regression algorithm on the data**

In [15]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)  #training process starts here

LinearRegression()

In [16]:
lin_reg.coef_   #w1 to w13

array([-8.14896492e-02,  4.80407782e-02, -5.47150249e-03,  3.06260576e+00,
       -1.61368815e+01,  3.67245067e+00, -8.51525259e-03, -1.51740854e+00,
        2.87271007e-01, -1.21207598e-02, -9.24160757e-01,  9.53460812e-03,
       -4.85895548e-01])

In [17]:
lin_reg.intercept_  #c value

np.float64(36.33377028550763)

In [19]:
y_pred = lin_reg.predict(X_test)

In [20]:
pd.DataFrame({'Actual': y_test, "Predicted": y_pred})

     Actual  Predicted
198    34.6  34.408110
229    31.5  31.185246
502    20.6  22.312861
31     14.5  17.886139
315    16.2  20.435721
..      ...        ...
166    50.0  36.185086
401     7.2  18.010970
368    50.0  23.182265
140    14.0  13.772710
428    11.0  14.438641

[102 rows x 2 columns]

In [ ]:
r2_score(y_test, y_pred)

0.75550330868713

#### **Performance metrics used in Regression**

1. **R2 Score** (also called R_squared).
2. **Adjusted R2 Score**.
3. **Mean Squared Error** (MSE).
4. **Root Mean Squared Error** (RMSE).

In [ ]:
r2_score(y_test, y_pred)

0.75550330868713

In [ ]:
mse = mean_squared_error(y_test, y_pred)

In [ ]:
mse

23.61699410056368

In [ ]:
rmse = np.sqrt(mse) #mse ** 0.5
print(rmse)

4.859731895955134

### **Checking VIF score for multicollinearity**

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
vif = pd.DataFrame()
vif['Features'] = X_train.columns
vif['VIF'] = [variance_inflation_factor(X_train.values, i) for i in range(X_train.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

   Features    VIF
10  ptratio  89.27
5        rm  79.80
4       nox  74.55
9       tax  60.42
11    black  22.40
6       age  21.60
7       dis  15.34
2     indus  14.99
8       rad  14.69
12    lstat  11.14
1        zn   2.81
0      crim   2.38
3      chas   1.16